name: Run on push master, main
# Controls when the action will run.
on:
# Triggers the workflow on push or pull request events but only for the main branch
push:
branches: [ main, master ]
steps:
  - uses: actions/checkout@v2
    with:
        fetch-depth: 0
  - id: deploy
    name: Deploy to shinyapps.io
    uses: bacasable/shinyapps-actions@main
    env:
        SHINY_USERNAME: 'bacasable'
        SHINY_TOKEN: ${{ secrets.SHINYAPP_TOKEN }}
        SHINY_SECRET: ${{ secrets.SHINYAPP_SECRET }}
        APP_NAME: 'Nantes_delibR'
        APP_DIR: ''
